### ISSUE TITLE
TS to OpenAPI does not produce descriptions from the comments

### ISSUE THREAD

**Issue by rattrayalex** [grantila/typeconv#13]
If I have a type like this:

```ts
type Point = {
  /** The distance from the left in mm */
  x: number;
  /** The distance from the top in mm */
  y: number;
};
```
I would hope for an OpenAPI spec like this:

```yaml
components:
  schemas:
    Point:
      type: object
      properties:
        x:
          type: number
          description: The distance from the left in mm
        y:
          type: number
          description: The distance from the top in mm
```

The primary reason I would want to convert my TS types to OpenAPI specs is so people can look at documentation for the API param/response types in a web browser.

Can this be done?
